version: '3'
services:
  web:
    stdin_open: true
    environment: 
    - CHOKIDAR_USEPOLLING=true
    ports:
    - "3000:3000"
    volumes:
    - /app/node_modules
    - .:/app
    build:
      context: .
      dockerfile: Dockerfile.dev
  test:
    stdin_open: true
    environment: 
    - CHOKIDAR_USEPOLLING=true
    volumes:
    - /app/node_modules
    - .:/app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]